### PR TITLE
Compatibility with Twing@5

### LINKED ISSUE #21: twing-loader is not compatible with Twing@4
Related to https://github.com/NightlyCommit/twing/issues/473

twing-loader is currently not supporting Twing@4 because of async support. Since async support is there to stay, it's time to upgrade twing-loader to a new major version that supports Twing@4.

### PR DESCRIPTION
**Pull request by hason**
Fixes #21, but for Twing@5.

Test fails due to https://github.com/NightlyCommit/twing/pull/513

### CODE REVIEW

**Comment by hason** [comment]
Test fails dur to https://github.com/NightlyCommit/twing/pull/519.

**Comment by christianwiedemann** [comment]
Is there a way I can help to push this PR forward? Think it is nearly done.

**Comment by JohnAlbin** [comment]
It took some work, but I managed to test this PR.

It needs some significant work.

1. A webpack loader is supposed to be a synchronous function that, if it requires async transforms, calls webpack's callback when it is finished transforming the loaded resource. Instead, this PR's twing-loader returns a Promise that then calls webpack's callback. This is unnecessary and aggravates point 2.
2. The compile and render functions in Twing are synchronous. The loadTemplate function is async. Fortunately, webpack has already loaded the Twig template for us; it is the `source` that is given to the twing-loader. But this PR wraps all the Twing code in Promises so that we can't perform the transform synchronously.

I've got some non-working code that starts to fix these issues, but GitHub really makes it hard to collaborate on one issue.

**Comment by ericmorand** [comment]
Replaced by #29

**Pull request closed without merging**
